workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: master
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
    scripts:
      - |
        # set up debug keystore
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - |
        # fetch db and sudachi.rs dict
        wget https://jp.xydustc.me/f/arujisho.db.zip -O db/arujisho.db.zip
        cd sudachi.rs
        sh prepare_diczip.sh
        cd ..
      - |
        # install rust
        brew install rustup
        rustup-init -y
        source "$HOME/.cargo/env"
        rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android aarch64-apple-ios
        cargo install cargo-ndk
        flutter build apk --release
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --release --no-codesign
      - |
        #!/bin/sh
        mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/arujisho.apk
        mkdir -p Payload
        mkdir -p build/ios/ipa
        mv ./build/ios/iphoneos/Runner.app Payload
        zip -r -y -9 Payload.zip Payload/Runner.app
        mv Payload.zip build/ios/ipa/arujisho.ipa
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/ios/ipa/*.ipa
      - '*.snap'
      - build/windows/**/*.msix
  debug:
    name: Debug
    max_build_duration: 60
    environment:
      flutter: master
      xcode: latest
      cocoapods: default
    scripts:
      - |
        # set up debug keystore
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - |
        #!/bin/sh
        wget https://jp.xydustc.me/f/arujisho.db.zip -O db/arujisho.db.zip
        sed -i'.bak' -e 's/isRelease = true/isRelease = false/g' lib/main.dart
      - flutter build apk --release
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --release --no-codesign
      - |
        #!/bin/sh
        mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/arujisho.apk
        mkdir -p Payload
        mkdir -p build/ios/ipa
        mv ./build/ios/iphoneos/Runner.app Payload
        zip -r -y -0 Payload.zip Payload/Runner.app
        mv Payload.zip build/ios/ipa/arujisho.ipa
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - '*.snap'
      - build/windows/**/*.msix
      - flutter_drive.log